### ISSUE TITLE
Newly installed Vagrant server has only one item in database

### ISSUE THREAD

**Issue by blackslate** [Tatoeba/imouto#66] opened 2020-05-30 17:13 UTC
I'm just starting working with you on Tatoeba, and I'd like to look at [issue 2093](https://github.com/Tatoeba/tatoeba2/issues/2093). I have set up a local instance of Tatoeba using the [README instructions](https://github.com/Tatoeba/imouto/blob/master/README.md). `vagrant up` lets me connect to `http://localhost:8080/eng/`, and `vagrant ssh` lets me use

    mysql tatoeba
    SELECT * FROM sentences;

In both cases, I see only 1 single sentence in the database. To reproduce issue 2093, I'll need to "find a sentence with many translations".  Presumably, this means installing a more complete database of sentences. How do I set about doing this?

**Comment by AndiPersti** [comment] 2020-05-30 18:23
We currently [don't have a database seeding script](https://github.com/Tatoeba/imouto/issues/59) so you need to create some sentences yourself.

**Comment by jiru** [comment] 2020-06-13 08:48
Closing this issue as a duplicate of Tatoeba/tatoeba2#2010.

**Closed by jiru** 2020-06-13 08:48 UTC
